name: âœ…ï¸ Test

on: [push, pull_request]

jobs:
  install:
    name: ğŸ“Œ Install (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Clone ğŸ‘€
        uses: actions/checkout@v2

      - name: Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ğŸ“Œ
        run: make install

  test:
    name: ğŸ¯ Test (Ubuntu)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Clone ğŸ‘€
        uses: actions/checkout@v2

      - name: Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ğŸ“Œ
        run: make develop

      - name: Test ğŸ¯
        run: make test

  cov:
    name: ğŸ†ï¸ Upload Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone ğŸ‘€
        uses: actions/checkout@v2

      - name: Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ğŸ“Œ
        run: make develop

      - name: Generate Report ğŸ—ï¸
        run: make cov

      - name: Upload Report ğŸ™ƒ
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
